<div>
<div id="page" class="bg1" data-url="confirmationdeal">
    <div class="wrapper">
        <div class="container">
            <div class="logo"></div>
            
            <div class="row-fluid deal">
                
                <div class="row-fluid">
                    <div class="span4 title">Investment Confirmation</div>
                    <a class="icon-angle-left back-deal iconback" href="/index" data-direction="right"></a>
                    <div class="clear"></div>
                </div>  

                <div style="margin-right: 3%;margin-left: 3%;">

                    <div class="hf-name" style="margin-left: 0;margin-top: 5%;color: #999;float:none;">
                        Resume
                    </div>
                    <div class="clear"></div>
                    <ul class="confirmation-deal">
                        <li><span class="cambria">Investment of <span class="resume-amount">1.000</span>€ in the deal "<span class="resume-product-name">Apple Sunrise</span>" provided by the hedge-fund "<span class="resume-hedgefund">Lansrode Capital</span>".</span></li>
                        <li><span class="attention">Maximum loss :</span> &nbsp;&nbsp;&nbsp;-<span class="resume-max-loss">20</span>% <span class="light">or</span> <span class="resume-max-loss-amount">200</span>€</li>
                        <li><span class="attention">Maximum gain :</span> &nbsp;&nbsp;&nbsp;+<span class="resume-max-gain">60</span>% <span class="light">or</span> <span class="resume-max-gain-amount">600</span>€</li>                        <li><span class="attention">Moneyspark's fees on gain :</span> &nbsp;&nbsp;&nbsp;<span class="resume-fee">9.2</span>%</li>
                    </ul>


                    <div class="hf-name" style="margin-left: 0;margin-top: 5%;color: #999;float:none;">
                        Payment method
                    </div>
                    <div style="float: left;margin-top: 3%;">
                        <div class="check-little-grey no-change" style="float:left;"></div>
                        <div class="check-text-little-grey" style="float:left;padding-left:0;">Credit card<br/><span style="font-style: italic; color: #888;">Soon available !</span></div>
                    </div>
                    <div style="float: right;margin-top: 3%;">
                        <div class="check-little-grey active no-change" style="float:left;"></div>
                        <div class="check-text-little-grey" style="float:left;padding-left:0;">Account cash<br/><span style="font-style: italic; color: #888;">Balance: <span class="resume-user-cash">1234.00</span>€</div>
                    </div>
                    <div class="clear"></div>

                    <div class="hf-name" style="margin-left: 0;margin-top: 3%;color: #999;float:none;">
                        Use of terms
                    </div>
                    <div style="float: left;margin-top: 2%;" data-role="checkbox">
                        <div class="check-little-grey terms" style="float:left;"></div>
                        <div class="check-text-little-grey">I've read and accepted the use of terms.</div>
                    </div>
                    <div style="float: left;margin-top: 2%;" data-role="checkbox">
                        <div class="check-little-grey risk" style="float:left;"></div>
                        <div class="check-text-little-grey">I know the risks of stock market investment.</div>
                    </div>
                    <div style="float: left;margin-top: 2%;" data-role="checkbox">
                        <div class="check-little-grey claim" style="float:left;"></div>
                        <div class="check-text-little-grey">I agree not to claim my loss if there is one.</div>
                    </div>
                    <div class="clear"></div>

                </div>

                <div class="button-bg2 zeroauto validate" style="margin-top: 10%"><i class="icon-ok-sign mr10" data-role="none"></i>validate</div>

            </div>
        </div>
    </div>
    <div class="footer">
        <div class="bottom-menu">
            <button id="showLeftPush" class="button-menuvertical">
                <div class="trait"></div>
                <div class="trait"></div>
                <div class="trait"></div>
            </button>
        </div>
    </div> 
</div>
</div>