    <nav class="menuvertical menuvertical-vertical menuvertical-left">
        <div class="mt34"></div>
        <div class="ensemble-menu">
        </div>
    </nav>
    <div id="page" class="bg1" data-url="deal">
        <div class="wrapper">
            <div class="container" id="deal-container">
                <div class="logo"></div>
                <div class="flip-container">
                    <div class="flipper">
                        <div class="front">
                            <div id="deal-model" class="row-fluid deal" style="display:none;float:left;display:none;">
                                <div class="row-fluid">
                                    <div class="span4 title">Apple Sunrise</div>
                                    <div class="clear"></div>
                                </div>  

                                <div class="row-fluid content">
                                    <div class="span3">
                                        <div class="logo-hf"></div>
                                        <div class="hf-name">Lansrode Capital</div>
                                        <div class="clear"></div>
                                    </div>
                                    <div class="span1">
                                        <div class="lock-icon"></div>
                                        <div class="lock-time">1 day</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>

                                <div class="row-fluid progress-mt">
                                    <div class="span3 mt4">
                                        <div class="row-fluid">
                                            <div class="progress-bar-layout"></div>
                                            <div class="progress-bar-hover"></div>
                                        </div>
                                        <div class="row-fluid">
                                            <div class="progress-number"><span class="maybe may-funded">founded</span></div>
                                        </div>
                                    </div>
                                    <div class="span1">
                                        <a class="imin">I'm in !</a>
                                    </div>
                                    <div class="clear"></div>
                                </div>

                                <div class="bordertop"></div>
                                <div class="borderbottom"></div>
                                <div class="buydeal">
                                    <div class="row-fluid">
                                        <div class="amount" style="float: left;">Amount to invest </div>
                                        <div class="amount" style="float: right;">€</div>                    
                                        <input type="number" class="input" style="float: right;cursor: pointer;" name="amount" placeholder="50"/>
                                        <div class="clear"></div>
                                    </div>
                                    <div class="row-fluid">
                                        <div class="fees" style="float: left;">our fees on gain</div>
                                        <div class="fees ml12" style="float: right;">%</div>
                                        <div class="fees" style="float: right;">0</div>
                                        <div class="clear"></div>
                                    </div>
                                    <div class="row-fluid">
                                        <button class="letsgo">GO</button>
                                    </div>
                                </div>

                                <div class="row-fluid">
                                    <div class="analyse"></div>
                                    <span class="text se">Analysis</span>
                                    <div class="clear"></div>
                                </div>    
                                <div class="row-fluid ana">    
                                    <div class="text">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet convallis ante, a commodo quam. Fusce bibendum sagittis ullamcorper. Cras facilisis quis massa sed tincidunt. Aenean a interdum mi etiam consectetur iaculis diam eget commodo. Vivamus facilisis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet convallis ante, a commodo quam. Fusce bibendum sagittis ullamcorper. Cras facilisis quis massa sed tincidunt. Aenean a interdum mi etiam consectetur iaculis diam eget<span class="seemore">- More...</span>
                                    </div>
                                </div>

                                <div class="bordertop"></div>
                                <div class="borderbottom"></div>

                                <div class="row-fluid zeroauto">


                                    <div class="span3 mt4">
                                        <div class="row-fluid" style="padding-right: 10%;">
                                            <div class="progress-number maybe" style="float: none;">Rentability max &amp; min</div>
                                            <div class="opportunity-bar-layout"></div>
                                        </div>
                                        <div class="row-fluid" style="padding-right: 10%;">
                                            <div class="progress-number loss-expected" style="float: left;">-20%</div>
                                            <div class="progress-number renta-expected" style="float: right;">+60%</div>
                                        </div>
                                    </div>
                                    <div class="span1 chrono-pt">
                                        <div class="sportwatch-icon"></div>
                                        <div class="sportwatch-time">1 week</div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="bottom-menu">
                <button id="showLeftPush" class="button-menuvertical">
                    <div class="trait"></div>
                    <div class="trait"></div>
                    <div class="trait"></div>
                </button>
                <div class="ensemble-pagenum-bottom-menu">
                    <a class="pagenum active" href="#prev" rel="1"></a>
                    <a class="pagenum center" href="#" rel="2"></a>
                    <a class="pagenum" href="#next" rel="3"></a>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
