<div>
    <div id="page" data-url="profile" class="bg2">
        <div class="wrapper">
            <div class="profil-header row-fluid">
                    <div class="user"></div>
                    <div class="cash-title"><span class="db-fullName"></span></div>
                <div class="clear"></div>
            </div>

            <div class="result positif">
                    <div class="a">
                        <span class="db-avgRentability"><span class="db-avgRentabilityText"></span> %</span>                    
                    </div>
                    <div class="b">
                        <span class="db-lockboxAmount">+ <span class="db-lockboxAmountText"></span> €</span>     
                    </div>
                    <div class="clear"></div>
            </div> 

            <div style="background-color:#fff;padding-top: 3%;color:#666"> 
                
                <div class="container myDeals" id="profileContainer"> 

                	<!--  model notStarted -->
                    <div class="deal-resume notStarted" style="display:none">
                        <div class="part">
                            <div class="title db-title">
                            </div>
                            <div class="money-result db-invested">
                                <span class="sumInvested"></span> €
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="part">
                            <div style="float:left;width:70%" class="db-progress-bar">
                                <div class="progress-bar-layout"></div>
                                <div class="progress-bar-hover"></div>
                            </div>
                            <div class="statut db-phrase">
                                <span class="ratioInvested"></span> %<span class="maybe may-funded"> founded</span>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>

					<!--  model current -->
                    <div class="deal-resume current" style="display:none">
                        <div class="part">
                            <div class="title">
                            </div>
                            <div class="money-result positif">
                                <span class="gain"></span> €
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="part">
                            <div style="float:left;width:70%">
                                <div class="opportunity-bar-layout"></div>
                                <div class="puce" style="margin-left: 0px;"></div>
                            </div>
                            <div class="statut">
                                <span class="rentability"></span> %
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>

					<!--  model ended -->
                    <div class="deal-resume ended" style="display:none">
                        <div class="part">
                            <div class="title">
                            </div>
                            <div class="money-result positif">
                                <span class="gain"></span> €
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="part">
                            	<div style="float:left;width:70%">
                                <div class="closeBar positif-bar-close"></div>
                            </div>
                            <div class="statut">
                                <span class="rentability"></span> %
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>





                   
                </div>    
            </div>
        </div>  
        <div class="footer">
            <div class="bottom-menu">
                <button id="showLeftPush" class="button-menuvertical">
                    <div class="trait"></div>
                    <div class="trait"></div>
                    <div class="trait"></div>
                </button>
            </div>
        </div> 
    </div>
</div>