<html>
    <head>
        <meta charset="utf-8" />
        <!-- <meta name="format-detection" content="telephone=no" /> -->
        <meta name="viewport" content="user-scalable=no, initial-scale=0.5" />
        <!-- Please don't add "maximum-scale=1" here. It's bad for accessibility. -->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=0.5"> -->
        <base href="<?php echo $this->url('front') ?>front/" />
        <link id="mycss" rel="stylesheet" type="text/css" href="css/front.css" />
        <title>Moneyspark</title>
    </head>
    <body class="bg2">
        <div class="grad"></div>
        <div class="container" style="padding-top:9%;z-index: 100;position: relative;">
        <?php echo $this->content; ?>
                <div class="text-site">
                    <img src="img/logo-site.png" class="logo-site"/>
                    <div class="clear"></div>
                    <div class="border anim"></div>
                    <div class="purpose">now... small capitals have access to big returns !</div>
                    <div class="download">iOS</div>
                    <div class="download" style="margin-right: 5%;">Android</div>
                    <div class="clear"></div>
                </div>
                <div class="app-pic">
                    <div class="app-site"></div>
                </div>
                <div class="clear"></div>
                <div class="menu-bottom">
                    <a class="section">ABOUT</a>
                    <a class="section">JOURNAL</a>
                    <a><i class="section-i icon-facebook-sign"></i></a>
                    <a href="https://twitter.com/Moneyspark"><i class="section-i icon-twitter"></i></a>
                    <a><i class="section-i icon-linkedin"></i></a>
                    <a><i class="section-i icon-google-plus"></i></a>
                </div>
        </div>
        <script type="text/javascript" src="js/jquery.js"></script>

        <!-- Only when compile on device !-->        
        <script type="text/javascript">
        $(window).load(function () {

            var wdt = $('.purpose').width();
            $('.border').width(wdt);

        });   


        </script>
    </body>
</html>