<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- <meta name="format-detection" content="telephone=no" /> -->
    <meta name="viewport" content="user-scalable=no, initial-scale=0.5" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <base href="<?php echo $this->url('mobile') ?>mobile/" />
    <link id="mycss" rel="stylesheet" type="text/css" href="css/mobile.css" />
    <title>Moneyspark</title>
</head>
<body class="menuvertical-push" data-url="deals">
<?php echo $this->content; ?>
    <sciprt type="text/javascript" src="js/mobile.min.js"></script>
</body>
</html>