<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- <meta name="format-detection" content="telephone=no" /> -->
    <meta name="viewport" content="user-scalable=no, initial-scale=0.5" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Please don't add "maximum-scale=1" here. It's bad for accessibility. -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=0.5"> -->
    <base href="<?php echo $this->url('mobile') ?>mobile/" />
    <link id="mycss" rel="stylesheet" type="text/css" href="css/mobile.css" />
    <title>Moneyspark</title>
</head>
<body class="menuvertical-push" data-url="deals">
<?php echo $this->content; ?>
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/jquery.inheritance.js"></script>
    <!-- <script type="text/javascript" src="cordova.js"></script> !-->
    <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="js/device.js"></script>
    <script type="text/javascript" src="js/transit.min.js"></script>
    <script type="text/javascript" src="js/jquery.touchSwipe.min.js"></script>
    <script type="text/javascript" src="js/sql.js"></script>
    <script type="text/javascript" src="js/rest.js"></script>
    <script type="text/javascript" src="js/project.js"></script>
</body>
</html>